### PR TITLE
support for multi traces in dataviz

### PR DESCRIPTION
**Pull request by Gustry**
* **Funded by**: Communauté d'agglomération du Grand Narbonne https://www.legrandnarbonne.com/
* **Ticket**: #238 
* **Description**: Support for multi traces in dataviz

For some graphs, we want to be able to add from 1 to N traces on the same graph.

Y, Y2, Z and colors are now hidden from the main table. It's a JSON representation. It's less user-friendly in the table. But I don't have a lot of choices because we can have 1-n traces for a single chart.

In the form, there is now a table to add/remove a trace:

Capture d’écran de 2020-03-25 09-39-22

Sélection_001

### CODE REVIEW

**Comment by Gustry** [comment]
Yes, the PR is now ready for testing.
Still need some polish:

* [ ] unicity
* [ ] export lizmap 3.4
* [ ] code review for myself
* [ ] clean tests

Use squash button

**Comment by Gustry** [comment]
Ok, travis is happy and me too.  ✌️✌️✌️
I could clean the code.

The only thing I'm wondering:

I have setup 3 traces on a chart.
If I set the plugin targetting LWC 3.4:

```
       "3": {
            "type": "bar",
            "title": "Average distance (m) during the day",
            "layerId": "v_daily_behaviour20180426180517739",
            "x_field": "event_hour",
            "aggregation": "avg",
            "traces": [
                {
                    "color": "#db06b1",
                    "colorfield": "",
                    "y_field": "distance",
                    "z_field": ""
                },
                {
                    "color": "#086fa1",
                    "colorfield": "",
                    "y_field": "cat_name",
                    "z_field": ""
                },
                {
                    "color": "#086fa1",
                    "colorfield": "",
                    "y_field": "speed_m_h",
                    "z_field": ""
                },
                {
                    "color": "#086fa1",
                    "colorfield": "",
                    "y_field": "event_hour",
                    "z_field": ""
                }
            ],
            "popup_display_child_plot": "True",
            "stacked": "False",
            "horizontal": "False",
            "only_show_child": "False",
            "display_legend": "True",
            "display_when_layer_visible": "False",
            "order": 3
        }
```

If I only change the target LWC version on the left of Lizmap plugin and I save the CFG again, I have:

```
        "3": {
            "type": "bar",
            "title": "Average distance (m) during the day",
            "layerId": "v_daily_behaviour20180426180517739",
            "x_field": "event_hour",
            "aggregation": "avg",
            "popup_display_child_plot": "True",
            "stacked": "False",
            "horizontal": "False",
            "only_show_child": "False",
            "display_legend": "True",
            "display_when_layer_visible": "False",
            "color": "#db06b1",
            "colorfield": "",
            "y_field": "distance",
            "z_field": "",
            "color2": "#086fa1",
            "colorfield2": "",
            "y2_field": "cat_name",
            "z_field_2": "",
            "color3": "#086fa1",
            "colorfield3": "",
            "y3_field": "speed_m_h",
            "z_field_3": "",
            "color4": "#086fa1",
            "colorfield4": "",
            "y4_field": "event_hour",
            "z_field_4": "",
            "order": 3
        }
```

I somehow didn't expect my code to work like that :)
So what should I do? Do you want to support only this new `traces` (and not write more than 2) or do you want to read `1,2,3...`?

**Comment by mdouchin** [comment]
You can leave it this way. I will try to support both.
Thanks a lots

**Comment by Gustry** [comment]
Ok, I'm ~merging~ squashing.
But I don't think we should support both.

**Pull request merged**
