### PR TITLE
New checkboxes for LWC 3.7 and EPSG:3857

### PR DESCRIPTION
**Pull request by Gustry**
image

* [x] Check the previous warning about legacy checkbox in baselayers and project not in 3857

### CODE REVIEW

**Comment by nboisteault** [comment]
@Gustry What about a button in the plugin which set the scales to those defined [here](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc)?

**Comment by Gustry** [comment]
> @Gustry What about a button in the plugin which set the scales to those defined [here](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc)?

This is not the best, as scales, as written in the documentation are "approximative". They depends on the latitude.

For instance : https://demo.lizmap.com/lizmap/index.php/view/map?repository=miscellaneous&project=qgis_info

* Zoom on Danemark: `1:1,278,470`
* **Only** pan the map over Corsica `1:1,709,959`
Which is not quite far, compare to North America and Ecuador.

The idea is to really behave like in this map https://demo.lizmap.com/lizmap/index.php/view/map?repository=miscellaneous&project=qgis_info scales are different according to the resolution.

**Comment by Gustry** [comment]
Side question, do we expect to uncheck these checkbox if something else than 3857 ?

For instance : 

1. the project is in 3857
2. The user plays with these checkbox
3. LWC uses these check-boxes, because they are in the CFG and project in 3857
4. The user changes the project CRS to 3857 to 2154, without opening Lizmap plugin, what happen in LWC ? Should we uncheck for him these checkbox in the plugin automatically ? (it's only hidden from the UI for now)

**Comment by Gustry** [comment]
Super-seeded by https://github.com/3liz/lizmap-plugin/pull/537

**Pull request closed without merging**
