### PR TITLE
multi atlas

### PR DESCRIPTION
**Pull request by Gustry**
Screenshot from 2019-11-13 12-06-15

To keep the compatibility with previous LWC:
if a single atlas in the table:
All JSON keys in the `options` section, with the `atlas` prefix. It should work with existing LWC because it's the same CFG file.
```json
{
    "options": {
        ..........
        "atlasMaxWidth": 25,
        "atlasDuration": 5,
        "atlasEnabled": "True",
        "atlasLayer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
        "atlasPrimarykey": "_code_chantier",
        "atlasDisplaylayerdescription": "True",
        "atlasFeaturelabel": "id",
        "atlasSortfield": "id",
        "atlasHighlightgeometry": "True",
        "atlasZoom": "",
        "atlasDisplaypopup": "True",
        "atlasTriggerfilter": "True",
        ..........
     }
}
```

If many atlas:
All JSON keys in a new `atlas` section, with a list of object. No `atlas` prefix. 
```json
{
    "options": {
        ..........
        "atlasMaxWidth": 25,
        "atlasDuration": 5,
        ..........
     }
    "atlas": [
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "displayPopup": true,
            "triggerFilter": true
        },
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "displayPopup": true,
            "triggerFilter": true
        }
    ]
}
```

**CODE not ready for review**
Just sharing so @nboisteault can have a look to the new CFG file.

@nboisteault This would work for you?
@mdouchin and @rldhont FYI
@dmarteau I need to check the the Lizmap API.

### CODE REVIEW

**Comment by nboisteault** [comment]
@Gustry CFG looks fine to me with changes asked in opened issues. Very nice UI !

**Comment by nboisteault** [comment]
@mdouchin should we keep `atlasMaxWidth` parameter ? It is not useful since 
 https://github.com/3liz/lizmap-web-client/commit/1db3ccf1d1293dcdc8a3830223b6f25b9af44639

**Comment by mdouchin** [comment]
no you can remove it, even if for the user it is simpler to give a size in the plugin than writing a CSS file specific for the QGIS project in media.

**Comment by Gustry** [comment]
Ok, I will remove it

**Comment by Gustry** [comment]
Ok, here the update about the new CFG file, if a single layer:

* no more maxWidth

```
{
    "options": {
        ..........
        "atlasAutoPlay":"True",
        "atlasShowAtStartup": "True",
        "atlasDuration": 5,
        "atlasEnabled": "True",
        "atlasLayer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
        "atlasPrimarykey": "_code_chantier",
        "atlasDisplaylayerdescription": "True",
        "atlasFeaturelabel": "id",
        "atlasSortfield": "id",
        "atlasHighlightgeometry": "True",
        "atlasZoom": "",
        "atlasDisplaypopup": "True",
        "atlasTriggerfilter": "True",
        ..........
     }
}
```

If multi-atlas:
```
{
    "options": {
        ..........
        "atlasAutoPlay":"True",
        "atlasShowAtStartup": "True",
        ..........
     }
    "atlas": [
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "duration": 5,
            "displayPopup": true,
            "triggerFilter": true
        },
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "duration": 10,
            "displayPopup": true,
            "triggerFilter": true
        }
    ]
}
```

I hope it's correct.

**Comment by nboisteault** [comment]
@Gustry If you replace boolean by string boolean, it is ok for me.

**Comment by Gustry** [comment]
> @Gustry If you replace boolean by string boolean, it is ok for me.

I understand your wish of having the same booleans ;-) No problem, I will rollback.

**Comment by Gustry** [comment]
Related ticket : 
* https://github.com/3liz/lizmap-plugin/issues/177
* https://github.com/3liz/lizmap-plugin/issues/173
* https://github.com/3liz/lizmap-plugin/issues/174

**Pull request closed without merging**
