### PR TITLE
Enable popup configuration of a project layer (Layers panel)

### PR DESCRIPTION
**Pull request by sylsta**
Dear all, 

Code suggestions to correct bugs noticed there :
https://github.com/3liz/lizmap-plugin/issues/111
https://github.com/3liz/lizmap-plugin/issues/117

Signed-off-by: Sylvain Théry <sylvain@thery.org>

### CODE REVIEW

**Comment by Gustry** [comment]
This is PR is against `master_3` which is a staled branch. For QGIS 3, the branch is `master`. For QGIS 2, the branch is called `qgis2`.

The error about QDesktopService has already been fixed in QGIS 3 : https://github.com/3liz/lizmap-plugin/blob/master/lizmap.py#L67

**Comment by sylsta** [comment]
Oupssss. Sorry.

**Comment by sylsta** [comment]
Oups, sorry. 
I'm gonna submit another pull request. 
Sorry for the inconvience.

**Comment by Gustry** [comment]
@rldhont @mdouchin Can you rename master_3 to something else to avoid confusion?

**Comment by rldhont** [comment]
@sylsta you can change the branch to merge in. I change form master_3 to master and it is good.
Can you re activate your branch ? no need to create a new branch or a new PR.

**Pull request closed without merging**
