### PR TITLE
UI - Add new panel for the filter by polygon

### PR DESCRIPTION
**Pull request by Gustry**
* **Funded by**:  Valabre
* **Description**: 
  * Add a new panel to have a filtering by polygon

Screenshot from 2021-07-27 17-09-34

Fixme :

Desktop :
* [x] Documentation Lizmap https://github.com/3liz/lizmap-documentation link in the definitions : PR https://github.com/3liz/lizmap-documentation/pull/184
* [x] Possible issue when reading the dictionnary, because the field depends on the layer for the general config
* [x] Filter layer by polygon icon in the menu
* [x] Fix help in the UI file

Server :  
* [x] Manage with the existing server code about ACL
* [x] Manage if the config is not valid, as we are talking about ACL, we should return 500 ? Use `where False` ?
* [x] Check header for edition with `X-Lizmap-Edition-Context`, why `X` BTW ?
* [x] Start lizmap documentation
* [x] Add a request to know if edition is possible ?
* [ ] LRU cache
* [ ] Editing is only available for postgres

### CODE REVIEW

**Comment by Gustry** [comment]
Currently generated CFG : 

```json
    "filter_by_polygon": {
        "config": {
            "polygon_layer_id": "parcelle_8f0b2cab_2e87_41f4_8758_b4bc3cd42ba5",
            "group_field": "geo_parcelle"
        },
        "layers": [
            {
                "layer": "Propri\u00e9taires_37bbc2c5_e6a7_4789_bcaa_a7290cbf5d43",
                "primary_key": "Noms",
                "filter_mode": "display_and_editing"
            },
            {
                "layer": "parcelle_8f0b2cab_2e87_41f4_8758_b4bc3cd42ba5",
                "primary_key": "geo_parcelle",
                "filter_mode": "display_and_editing"
            }
        ]
    },
```

**Comment by mdouchin** [comment]
Should I review this PR before you fix the 4 checkboxes ?

**Comment by Gustry** [comment]
I have fixed everything.
Ready for merge @mdouchin 

Just waiting for the online help URL : https://github.com/3liz/lizmap-plugin/pull/355/files#diff-58cd5d458b52a1f897326f4571e34a0b4dbe321061ca37834fffd076eeb88f46R72

**Review by mdouchin — APPROVED** [review]
I love the png icons before the "Display and editing" and "Editing only" values

**Comment by Gustry** [comment]
Yes !

I love "less" the icon for the panel itself ;-)

**Comment by Gustry** [comment]
All tests are passing @mdouchin so at least you can try with LWC for "display"

Todo : 

* [ ] LRU cache
* [ ] Manage with the existing server code about ACL
* [ ] Manage if the config is not valid, as we are talking about ACL, you should give 500.
* [ ] Check header for edition

**Comment by Gustry** [comment]
Ready for review @rldhont and @mdouchin 
The code is integrated with existing filter.

Maybe just the lrucache needs some improvments and checks.

**Comment by Gustry** [comment]
@mdouchin I would appreciate your review on the latest commit : "Make the SQL query straight to PostGIS if possible for the polygon filter layer"

**Pull request merged**
