### PR TITLE
Maptip - An HTML div can not be in a p tag

### PR DESCRIPTION
**Pull request by Gustry**
* **Funded by**: 3Liz
* **Description**: 
  * A `div` was previously included in a `p` tag.

I'm trying to add some tests for #341 but the linter is failing because of invalid result. It might be the cause.
https://stackoverflow.com/questions/5441639/how-can-i-put-div-in-p
I have error on many tools like PyCharm or  https://www.freeformatter.com/html-validator.html 

I will try to check the CSS

### CODE REVIEW

**Review by mdouchin — COMMENTED** [review]
Indeed a span is better than a div here. But note that:

* It would also remove the line-break between the field name and the value, since the span will display inline. I think it is better this way, but it could change the "look&feel" of the popup. 
* it is not possible to add sub-items in the span, since it should only contain text (the div can contain elements)

**Comment by Gustry** [comment]
Capture d’écran de 2021-06-11 17-17-14

Small glitch

**Comment by mdouchin** [comment]
> Small glitch

This is what I tried to explain with

> It would also remove the line-break between the field name and the value, since the span will display inline. I think it is better this way, but it could change the "look&feel" of the popup.

We could 

* add a <br/> before the value which is simple but uggly ;) if we want to keep the line-break
* use a table instead, to have the same look and feel that the Auto popup.

**Comment by rldhont** [comment]
I was in favor of a `<br/>` before the span or do not use `span` and replace `p` by `div` with some classes.

**Review by rldhont — CHANGES_REQUESTED** [review]
`<br/>` or `div` instead of `p`

**Pull request closed without merging**
