### PR TITLE
Update locales

### PR DESCRIPTION
**Pull request by rldhont**
Replace code string by the string itself
Use script update-strings

### CODE REVIEW

**Comment by rldhont** [comment]
Can you review it? I'd like to update lizmap-locales. Thanks

**Comment by pcav** [comment]
Will do ASAP. Which files should I take care of? Or should I use Transifex?
I'd be grateful if you could point me out the translation howto, if available.

**Comment by rldhont** [comment]
Hi @pcav, you should use Transifex.
I proposed this pull-request to simplify localization on Transifex.

**Comment by pcav** [comment]
Please not that upstream there are some errors:
* inconsistent capitalization of Lizmap vs Lizmap
* full stop at the end of some period

**Comment by pcav** [comment]
Moreover, there is a large number of repeated strings: would it be possible to merge them, for greater consistency and faster translations?

**Comment by rldhont** [comment]
@pcav the commit 7223132bf3a1ccf7652330731cc6531298ef4c46 done some correction
* inconsistent capitalization of LizMap vs Lizmap
* no repeated strings
I'll update lizmap-locales and transifex will be updated tomorrow

**Comment by rldhont** [comment]
lizmap-locales has been updated https://github.com/3liz/lizmap-locales/commit/ae08ba92559739aafe670771150fb80661bc8014
Transifex will be tomorrow

**Pull request merged**
