### PR TITLE
Get feature info

### PR DESCRIPTION
**Pull request by Gustry**
* **Funded by**: French Province Pyrénées-Atlantiques https://www.le64.fr/
* **Description**: 
  * Get the GetFeatureInfo from QGIS Server with the QGIS Form

@rldhont Should we use our own service/api ?
Or do you want to plug on the GetFeatureInfo request ?

I started on the GetFeatureInfo request as we can see on this draft.
But what would the best workflow ? 
1. Get the result from QGIS Server
2. Parse the result (HTML, GML etc) to have vector layer name and fature ID
3. Make again the QGIS project (to have relations). It seems in a QgsFilter, I couldn't have the Project used.
4. Call the class `Maptip` from Lizmap plugin with QgsVectorLayer and QgsProject

This doesn't seem efficient at all and very fragile so I would like to have your inputs.

At least, by writing the test file provided, I learned that the maptip is **inserted** in the HTML output, not replaced. So then I then I thought I would follow the same pattern.

### CODE REVIEW

**Comment by Gustry** [comment]
@rldhont Tests are passing and it's feature complete.

It just needs some polish, but I would like to check the behavior for now.

* What happen for instance when you make a GetFeatureInfo without the "with_maptip" get param, but some layers use the "qgis" or "form" popup source.

* This has no effect on LWC. It's not really a LWC 3.5 feature, but only QGIS Plugin side. We can promote it without waiting for 3.5 ?

**Comment by Gustry** [comment]
Before merging and polishing, I will wait for the dev in LWC to have some feedbacks.

**Comment by rldhont** [comment]
PR done for LWC

**Comment by Gustry** [comment]
* [x] PR on QGIS Lizmap server, ready
* [x] PR on LWC https://github.com/3liz/lizmap-web-client/pull/2326
* [x] PR on Lizmap documentation https://github.com/3liz/lizmap-documentation/commit/a96daf5d1696bf8b904108f9f4848f7936f5040a
* [ ] GIF, tweet

**Pull request merged**
