### PR TITLE
Add warning about Z or M values

### PR DESCRIPTION
**Pull request by Gustry**
Issue: https://github.com/3liz/lizmap-web-client/issues/902

* Fixing missing imports when opening the help
* Add more languages at the same time ;-)
* Add a warning when a layer has some Z or M values

I can backport to master.

### CODE REVIEW

**Comment by mdouchin** [comment]
I will probably change de names of the branches. 

* master_3 becomes master : new features only for QGIS 3
* master becomes master_2 : only bugfixes for QGIS 2

I first need to merge the laster work made on the current master into master_3. I will let you know asap

**Comment by mdouchin** [comment]
I have just merged master_3 into master. Please do not use master_3 anymore, as master is now the principal branch, only compatible with QGIS 3

I created a new qgis2 branch to target QGIS 2 (mainly bugfixes)

Could you please change your PR accordingly ? Backport into qgis2 is welcomed too :)

**Comment by mdouchin** [comment]
Thanks !

**Comment by Gustry** [comment]
So do you still want me to backport?
I think all my fixes in this PR might be present in the `qgis2` branch.

**Comment by Gustry** [comment]
And why not removing `master_3` to avoid confusion?

**Comment by rldhont** [comment]
@dmarteau do you think we can remove `master_3` ?

**Comment by rldhont** [comment]
@Gustry we still want the backport, do you think we can cherry-pick commits ?

**Pull request merged**
